apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports-api
  template:
    metadata:
      labels:
        app: reports-api
    spec:
      containers:
        - name: api
          image: local/reports-api:dev
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: "5"
              memory: 64Mi
